services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: abh_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: mi_base_de_datos
      MYSQL_USER: abh_user
      MYSQL_PASSWORD: abh_password
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/data/01_seed_data.sql:/docker-entrypoint-initdb.d/02_seed_data.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
    driver: local
